language: python
cache: pip
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=docs-deploy
install:
  - pip install tox
script:
  - tox
after_success:
  - pwd
  - ls -la
  - bash <(curl -s https://codecov.io/bash) -f coverage.xml
