language: python
cache: pip
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=docs-deploy
    - python: 3.7
      env: TOXENV=py37
      dist: xenial
      sudo: true
install:
  - pip install tox
script:
  - tox
after_success:
  - pwd
  - ls -la
  - bash <(curl -s https://codecov.io/bash) -f coverage.xml
