language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - env: TOXENV=flake8
install:
  - pip install tox codecov
script:
  - tox
after_success:
  - pwd
  - ls -la
  - codecov
